package com.mea.happyclients.errors;

/**
 * Provides a list of error codes generated by the application
 */

public class Errors {

    public final static int ERR_OK  = 0;

    //Database Errors
    public final static int ERR_DB_UNKOWN           = 1000;
    public final static int ERR_DB_DUPLICATE_ENTRY  = 1001;

    //UI errors
    public final static int ERR_UI_UNKOWN                   = 2000;
    public final static int ERR_UI_REG_PASSWORDS_DONT_MATCH = 2001;
    public final static int ERR_UI_REG_PASSWORD_WEAK        = 2002;
    public final static int ERR_UI_LOGIN_FAILED             = 2010;

}
